/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["getArtifactMetadataV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Cards */
        get: operations["listModelCardsV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Card */
        get: operations["getModelCardV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Openapi */
        get: operations["getOpenApiV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRunsV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRunV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["listRunArtifactsV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diagnostics */
        get: operations["listDiagnosticsV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/forecast-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forecast Summaries */
        get: operations["listAggregateForecastSummariesV1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactClass
         * @description Closed artifact classes accepted by the content-addressed store.
         * @enum {string}
         */
        ArtifactClass: "input" | "output" | "model" | "report" | "plot" | "log" | "metadata";
        /**
         * ArtifactPageResponse
         * @description Bounded keyset page of role-linked artifact metadata.
         */
        ArtifactPageResponse: {
            /** Items */
            items: components["schemas"]["RunArtifactResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * ArtifactResponse
         * @description Verified artifact metadata without bytes or a storage pathname.
         */
        ArtifactResponse: {
            artifact_class: components["schemas"]["ArtifactClass"];
            /** Artifact Id */
            artifact_id: string;
            /** Byte Size */
            byte_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Media Type */
            media_type: string;
            /** Pinned */
            pinned: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * DiagnosticCategory
         * @description Closed diagnostic families exposed by the public projection.
         * @enum {string}
         */
        DiagnosticCategory: "calibration" | "uncertainty" | "latency" | "lineage" | "readiness";
        DiagnosticScalar: boolean | number | string;
        /**
         * DiagnosticStatus
         * @description Decision state attached to one diagnostic value.
         * @enum {string}
         */
        DiagnosticStatus: "pass" | "warn" | "fail" | "informational";
        /**
         * DiagnosticValue
         * @description One bounded scalar diagnostic; arbitrary recursive JSON is forbidden.
         */
        DiagnosticValue: {
            category: components["schemas"]["DiagnosticCategory"];
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            status: components["schemas"]["DiagnosticStatus"];
            /** Unit */
            unit?: string | null;
            value: components["schemas"]["DiagnosticScalar"];
        };
        /**
         * DiagnosticsPageResponse
         * @description Bounded page of strict diagnostic manifests.
         */
        DiagnosticsPageResponse: {
            /** Items */
            items: components["schemas"]["DiagnosticsResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * DiagnosticsResponse
         * @description Diagnostics manifest with a canonical public run reference.
         */
        DiagnosticsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Kind
             * @default diagnostics
             * @constant
             */
            kind: "diagnostics";
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Values */
            values: components["schemas"]["DiagnosticValue"][];
        };
        /**
         * EvidenceClass
         * @description Honest provenance classification for execution evidence.
         * @enum {string}
         */
        EvidenceClass: "measured" | "simulated" | "backtested" | "paper_traded" | "live" | "not_applicable";
        /**
         * EvidenceReadinessCode
         * @description Closed, redacted outcome taxonomy for the complete evidence boundary.
         * @enum {string}
         */
        EvidenceReadinessCode: "ready" | "registry_missing" | "registry_busy" | "registry_authority_mismatch" | "registry_integrity_failed" | "registry_not_ready" | "cas_unbound" | "cas_missing" | "cas_not_initialized" | "cas_identity_mismatch" | "cas_integrity_failed" | "cas_unavailable";
        /**
         * ForecastAggregate
         * @description Multi-observation forecast evidence with no row- or instrument-level values.
         */
        ForecastAggregate: {
            /** Aggregate Id */
            aggregate_id: string;
            /** Horizon Steps */
            horizon_steps: number;
            horizon_unit: components["schemas"]["HorizonUnit"];
            /** Interval Coverage */
            interval_coverage?: number | null;
            /** Mean Absolute Error */
            mean_absolute_error: number;
            /** Mean Error */
            mean_error: number;
            /** Mean Interval Width */
            mean_interval_width?: number | null;
            /** Mean Observation */
            mean_observation: number;
            /** Mean Prediction */
            mean_prediction: number;
            /** Root Mean Squared Error */
            root_mean_squared_error: number;
            /** Sample Count */
            sample_count: number;
            split: components["schemas"]["ForecastSplit"];
            /** Target */
            target: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /**
         * ForecastSplit
         * @description Closed temporal split labels for forecast evaluation aggregates.
         * @enum {string}
         */
        ForecastSplit: "train" | "validation" | "test" | "shadow";
        /**
         * ForecastSummaryPageResponse
         * @description Bounded page of aggregate-only forecast manifests.
         */
        ForecastSummaryPageResponse: {
            /**
             * Evidence Granularity
             * @default aggregate
             * @constant
             */
            evidence_granularity: "aggregate";
            /** Items */
            items: components["schemas"]["ForecastSummaryResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Row Level Available
             * @default false
             * @constant
             */
            row_level_available: false;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * ForecastSummaryResponse
         * @description Aggregate forecast manifest with a canonical public run reference.
         */
        ForecastSummaryResponse: {
            /** Aggregates */
            aggregates: components["schemas"]["ForecastAggregate"][];
            /**
             * Evidence Granularity
             * @default aggregate
             * @constant
             */
            evidence_granularity: "aggregate";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Kind
             * @default forecast_summary
             * @constant
             */
            kind: "forecast_summary";
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /**
             * Row Level Available
             * @default false
             * @constant
             */
            row_level_available: false;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * HorizonUnit
         * @description Units supported by aggregate forecast horizons.
         * @enum {string}
         */
        HorizonUnit: "bars" | "calendar_days" | "business_days";
        /**
         * LiveResponse
         * @description Storage-independent process liveness.
         */
        LiveResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Status
             * @default live
             * @constant
             */
            status: "live";
        };
        /**
         * ModelCardManifestResponse
         * @description Structured model card with a canonical public run reference.
         */
        ModelCardManifestResponse: {
            /** Card Id */
            card_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Kind
             * @default model_card
             * @constant
             */
            kind: "model_card";
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Sections */
            sections: components["schemas"]["ModelCardSection"][];
            /**
             * Text Format
             * @default plain_text
             * @constant
             */
            text_format: "plain_text";
        };
        /**
         * ModelCardPageResponse
         * @description Bounded run-scoped page of model-card summaries.
         */
        ModelCardPageResponse: {
            /** Items */
            items: components["schemas"]["ModelCardSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * ModelCardResponse
         * @description One verified structured plain-text model card.
         */
        ModelCardResponse: {
            /** Artifact Id */
            artifact_id: string;
            model_card: components["schemas"]["ModelCardManifestResponse"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * ModelCardSection
         * @description One named plain-text model-card section with no rendering semantics.
         */
        ModelCardSection: {
            name: components["schemas"]["ModelCardSectionName"];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /**
         * ModelCardSectionName
         * @description Ordered, closed sections allowed in a structured model card.
         * @enum {string}
         */
        ModelCardSectionName: "overview" | "intended_use" | "out_of_scope_use" | "data" | "evaluation" | "limitations" | "ethical_considerations" | "monitoring";
        /**
         * ModelCardSummary
         * @description Small model-card listing projection.
         */
        ModelCardSummary: {
            /** Artifact Id */
            artifact_id: string;
            /** Card Id */
            card_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Limitation Count */
            limitation_count: number;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * OpenApiDocument
         * @description This service's own OpenAPI 3.1 document. Conformance to the OpenAPI meta-schema is asserted by the contract test suite rather than by a remote $ref, so the published contract resolves entirely offline.
         */
        OpenApiDocument: {
            [key: string]: unknown;
        };
        /**
         * ProblemDocument
         * @description RFC 9457 response with a stable service code and server request ID.
         */
        ProblemDocument: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Request Id */
            request_id: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * ReadyResponse
         * @description Redacted bounded registry/CAS readiness verdict.
         */
        ReadyResponse: {
            code: components["schemas"]["EvidenceReadinessCode"];
            /** Journal Mode */
            journal_mode?: ("wal" | "delete") | null;
            /** Ready */
            ready: boolean;
            /** Registry Schema Version */
            registry_schema_version?: number | null;
            /** Retryable */
            retryable: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * RunArtifactResponse
         * @description One immutable evidence role and its verified metadata projection.
         */
        RunArtifactResponse: {
            artifact: components["schemas"]["ArtifactResponse"];
            /**
             * Linked At
             * Format: date-time
             */
            linked_at: string;
            /** Role */
            role: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * RunEvidenceLinks
         * @description Relative versioned links available for one run projection.
         */
        RunEvidenceLinks: {
            /** Artifacts */
            artifacts: string;
            /** Diagnostics */
            diagnostics: string;
            /** Forecast Summaries */
            forecast_summaries: string;
        };
        /**
         * RunPageResponse
         * @description Bounded keyset page of run projections.
         */
        RunPageResponse: {
            /** Items */
            items: components["schemas"]["RunResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * RunProvenance
         * @description Trust classification for a framework-neutral run projection.
         * @enum {string}
         */
        RunProvenance: "registry/verified" | "legacy/unverified";
        /**
         * RunResponse
         * @description Path-free public run projection for durable or legacy evidence.
         */
        RunResponse: {
            /** Created At */
            created_at: string | null;
            /** Data Identity */
            data_identity: string | null;
            /** Ended At */
            ended_at: string | null;
            evidence_class: components["schemas"]["EvidenceClass"] | null;
            /** Limitation Summary */
            limitation_summary: string | null;
            links: components["schemas"]["RunEvidenceLinks"];
            provenance: components["schemas"]["RunProvenance"];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Sequence */
            sequence: number;
            /** Source Commit */
            source_commit: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"] | null;
        };
        /**
         * RunStatus
         * @description Closed terminal status for an immutable execution-run record.
         * @enum {string}
         */
        RunStatus: "succeeded" | "failed" | "cancelled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getArtifactMetadataV1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listModelCardsV1: {
        parameters: {
            query: {
                run_id: string;
                /** @description Page size; default 25, maximum 100. */
                page_size?: number;
                /** @description Opaque authenticated keyset cursor. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCardPageResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    getModelCardV1: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCardResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    getOpenApiV1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deterministic OpenAPI 3.1 service contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDocument"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listRunsV1: {
        parameters: {
            query?: {
                /** @description Page size; default 25, maximum 100. */
                page_size?: number;
                /** @description Opaque authenticated keyset cursor. */
                cursor?: string | null;
                status?: components["schemas"]["RunStatus"] | null;
                provenance?: components["schemas"]["RunProvenance"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPageResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    getRunV1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listRunArtifactsV1: {
        parameters: {
            query?: {
                /** @description Page size; default 25, maximum 100. */
                page_size?: number;
                /** @description Opaque authenticated keyset cursor. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPageResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listDiagnosticsV1: {
        parameters: {
            query?: {
                /** @description Page size; default 25, maximum 100. */
                page_size?: number;
                /** @description Opaque authenticated keyset cursor. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsPageResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    listAggregateForecastSummariesV1: {
        parameters: {
            query?: {
                /** @description Page size; default 25, maximum 100. */
                page_size?: number;
                /** @description Opaque authenticated keyset cursor. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSummaryPageResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The requested safe evidence projection does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A typed query or path value failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description The service is draining or a verified evidence or response boundary is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description The bounded request contract was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Only GET is supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Request bodies are forbidden. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description A bounded rate or concurrency admission limit was reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description An unexpected failure was redacted at the service boundary. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
            /** @description Storage is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                    "application/problem+json": components["schemas"]["ProblemDocument"];
                };
            };
        };
    };
}
