"""Robustness analysis: parameters, features, calendar, regimes, and universe.

- :mod:`~alphaforge.robustness.grid` — the frozen study: parameter axes, feature
  families, ablation arms, negative controls, and named seed streams, published
  with a content identity so a mid-study edit is detectable.
- :mod:`~alphaforge.robustness.controls` — feature-permutation, randomized-label,
  and representation-placebo nulls under a leakage-safe temporal protocol.
- :mod:`~alphaforge.robustness.stability` — stable regions, sensitivity cliffs,
  and family redundancy, reported instead of a single optimum.
- :mod:`~alphaforge.robustness.periods` — calendar intervals and causal regime
  labels frozen before evaluation, so a regime is never defined from the
  outcomes it is used to explain.
- :mod:`~alphaforge.robustness.universe` — point-in-time membership and
  ablations, keeping investability filters distinct from hindsight-based
  fragility probes.
- :mod:`~alphaforge.robustness.perturbation` — frozen Monte Carlo perturbation of
  the execution path (order, price, timing, misses, size, cost, liquidity,
  fills) with structured failure reports and exact per-path replay.
- :mod:`~alphaforge.robustness.temporal_evidence` — per-period and per-regime
  evidence with block-bootstrap and Newey-West uncertainty, and the gate that
  withholds every portfolio-level claim absent a qualified candidate.

Simulation-only. Nothing here qualifies a strategy or claims a profit.
"""

from alphaforge.robustness.controls import (
    MIN_CONTROL_OBSERVATIONS,
    ControlOutcome,
    Fold,
    NegativeControlError,
    assert_streams_isolated,
    contiguous_folds,
    permute_within_folds,
    randomize_labels_within_folds,
    representation_placebo,
    run_control,
)
from alphaforge.robustness.grid import (
    CONTROL_KINDS,
    MAX_GRID_POINTS,
    ControlKind,
    FeatureFamily,
    GridPoint,
    NegativeControl,
    RobustnessGrid,
    RobustnessGridError,
    canonical_digest,
    verify_frozen,
)
from alphaforge.robustness.periods import (
    MIN_PERIOD_OBSERVATIONS,
    FrozenPeriodSet,
    PeriodContractError,
    PeriodInterval,
    RegimeDefinition,
    assert_conditioning_is_independent,
    calendar_years,
    coverage_report,
    label_regimes,
    standard_regime_definitions,
    verify_frozen_periods,
)
from alphaforge.robustness.perturbation import (
    MAX_MAGNITUDE,
    MIN_REPLICATES,
    PERTURBATION_KINDS,
    FrozenPerturbationGrid,
    InsolventPathError,
    PathOutcome,
    PerturbationError,
    PerturbationOutcome,
    PerturbationSpec,
    assert_perturbation_streams_isolated,
    evaluate_path,
    failure_report,
    perturb_path,
    replay_path,
    run_perturbation_study,
    standard_execution_grid,
    verify_frozen_perturbations,
)
from alphaforge.robustness.stability import (
    FamilyContribution,
    SensitivityCliff,
    StabilityError,
    StableRegion,
    family_redundancy,
    sensitivity_cliffs,
    stability_report,
    stable_regions,
    verify_rerun_determinism,
)
from alphaforge.robustness.temporal_evidence import (
    MIN_BOOTSTRAP_OBSERVATIONS,
    PeriodOutcome,
    QualifiedCandidate,
    TemporalEvidenceError,
    UncertaintyInterval,
    UnqualifiedCandidateError,
    block_bootstrap_interval,
    compare_uncertainty,
    matched_family_evidence,
    naive_interval,
    newey_west_interval,
    newey_west_standard_error,
    period_evidence,
    portfolio_dependence_evidence,
    regime_definition_sensitivity,
    regime_evidence,
    temporal_robustness_report,
)
from alphaforge.robustness.universe import (
    AblationResult,
    MembershipRecord,
    PointInTimeUniverse,
    UniverseContractError,
    apply_liquidity_floor,
    assert_no_future_membership,
    concentration_profile,
    drop_sector,
    drop_top_contributors,
    exclude_inactive,
)

__all__ = [
    "AblationResult",
    "CONTROL_KINDS",
    "ControlKind",
    "ControlOutcome",
    "FamilyContribution",
    "FeatureFamily",
    "Fold",
    "FrozenPeriodSet",
    "FrozenPerturbationGrid",
    "GridPoint",
    "InsolventPathError",
    "MAX_GRID_POINTS",
    "MAX_MAGNITUDE",
    "MIN_BOOTSTRAP_OBSERVATIONS",
    "MIN_CONTROL_OBSERVATIONS",
    "MIN_PERIOD_OBSERVATIONS",
    "MIN_REPLICATES",
    "MembershipRecord",
    "NegativeControl",
    "NegativeControlError",
    "PERTURBATION_KINDS",
    "PathOutcome",
    "PeriodContractError",
    "PeriodInterval",
    "PeriodOutcome",
    "PerturbationError",
    "PerturbationOutcome",
    "PerturbationSpec",
    "PointInTimeUniverse",
    "QualifiedCandidate",
    "RegimeDefinition",
    "RobustnessGrid",
    "RobustnessGridError",
    "SensitivityCliff",
    "StabilityError",
    "StableRegion",
    "TemporalEvidenceError",
    "UncertaintyInterval",
    "UniverseContractError",
    "UnqualifiedCandidateError",
    "apply_liquidity_floor",
    "assert_conditioning_is_independent",
    "assert_perturbation_streams_isolated",
    "assert_no_future_membership",
    "assert_streams_isolated",
    "block_bootstrap_interval",
    "calendar_years",
    "canonical_digest",
    "compare_uncertainty",
    "concentration_profile",
    "contiguous_folds",
    "coverage_report",
    "drop_sector",
    "drop_top_contributors",
    "evaluate_path",
    "exclude_inactive",
    "failure_report",
    "family_redundancy",
    "label_regimes",
    "matched_family_evidence",
    "naive_interval",
    "newey_west_interval",
    "newey_west_standard_error",
    "period_evidence",
    "permute_within_folds",
    "perturb_path",
    "portfolio_dependence_evidence",
    "randomize_labels_within_folds",
    "regime_definition_sensitivity",
    "regime_evidence",
    "replay_path",
    "representation_placebo",
    "run_control",
    "run_perturbation_study",
    "sensitivity_cliffs",
    "stability_report",
    "stable_regions",
    "standard_execution_grid",
    "standard_regime_definitions",
    "temporal_robustness_report",
    "verify_frozen",
    "verify_frozen_periods",
    "verify_frozen_perturbations",
    "verify_rerun_determinism",
]
