"""Type contract for the optional pybind11 execution extension."""

from enum import Enum

__abi_version__: str

class Side(Enum):
    BUY = ...
    SELL = ...

class Fill:
    maker_id: int
    taker_id: int
    price: int
    qty: int

    def as_tuple(self) -> tuple[int, int, int, int]: ...

class OrderBook:
    def __init__(self) -> None: ...
    def add_limit(self, side: Side, price: int, qty: int) -> int: ...
    def add_market(self, side: Side, qty: int) -> int: ...
    def cancel(self, order_id: int) -> bool: ...
    def best_bid(self) -> int | None: ...
    def best_ask(self) -> int | None: ...
    def bid_depth(self, levels: int = 10) -> list[tuple[int, int]]: ...
    def ask_depth(self, levels: int = 10) -> list[tuple[int, int]]: ...
    def bid_volume(self) -> int: ...
    def ask_volume(self) -> int: ...
    def open_orders(self) -> int: ...
    def take_fills(self) -> list[Fill]: ...
    def clear(self) -> None: ...

def simulate_fill(
    side: Side,
    qty: int,
    mid: int,
    half_spread: int,
    tick: int = 1,
    n_levels: int = 10,
    qty_per_level: int = 1000,
) -> tuple[float, int]: ...
