"""Deterministic Sprint 4 close-out evidence (SF-S4-MR8/MR9).

Publishes the sprint's machine-readable evidence and its Seaborn figure from a
single deterministic synthetic path. Everything here is **simulation on
synthetic data**: the purpose is to demonstrate that the sprint's machinery
produces honest evidence, not to claim a strategy works.

The figure deliberately shows the sprint's *adverse* outcomes beside its
favorable ones — the perturbation downside, the drawdown amplification under
reordering, and a qualification verdict of ``REJECTED`` for the candidate the
sprint actually has. A close-out plot that showed only what worked would fail
the evidence standard it is meant to satisfy.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

import numpy as np
import pandas as pd

from alphaforge.research.qualification import (
    EvidenceLink,
    QualificationDecision,
    qualify,
    render_dossier,
    standard_paper_rubric,
)
from alphaforge.robustness.perturbation import (
    failure_report,
    run_perturbation_study,
    standard_execution_grid,
)

#: Bounded, deterministic synthetic development path. Fixed so the published
#: evidence is reproducible from the committed script alone.
SYNTHETIC_SEED: Final = 20260802
SYNTHETIC_BARS: Final = 756
SYNTHETIC_DRIFT: Final = 0.00035
SYNTHETIC_VOLATILITY: Final = 0.011
SYNTHETIC_COST: Final = 0.00025
STUDY_REPLICATES: Final = 500
STUDY_SEED: Final = 4


class SprintEvidenceError(RuntimeError):
    """Raised when evidence cannot be published honestly."""


def synthetic_candidate_path() -> tuple[pd.Series, pd.Series]:
    """Return the frozen synthetic return and cost path.

    Deterministic by construction: the same seed, length, drift, and volatility
    every run, so the published figure can be regenerated byte-comparably.
    """
    generator = np.random.default_rng(SYNTHETIC_SEED)
    index = pd.bdate_range("2021-01-04", periods=SYNTHETIC_BARS)
    returns = pd.Series(
        generator.normal(SYNTHETIC_DRIFT, SYNTHETIC_VOLATILITY, SYNTHETIC_BARS), index=index
    )
    costs = pd.Series(np.full(SYNTHETIC_BARS, SYNTHETIC_COST), index=index)
    return returns, costs


def sprint_4_decision(study: dict[str, Any]) -> QualificationDecision:
    """Score the sprint's synthetic candidate against the frozen rubric.

    The observations come from the stress study where the stress study measures
    them. The remaining criteria — multiple-testing correction, risk
    attribution, capacity, and dependence-aware uncertainty — have **no
    qualifying evidence in Sprint 4**, so they are deliberately left unsupplied
    and the decision comes back ``REJECTED``.

    That is the honest result, and it is the one the gate is supposed to
    produce: a synthetic development path with no trial ledger and no capacity
    measurement has not earned paper trading.
    """
    rubric = standard_paper_rubric()
    outcomes = study["outcomes"]
    worst_downside = min(item["percentile_5"] for item in outcomes)
    insolvent = sum(item["insolvent_paths"] for item in outcomes)
    worst_drawdown = min(item["worst_max_drawdown"] for item in outcomes)

    observations = {
        "net_return_over_baseline": float(study["baseline"]["net_return"]),
        "stress_downside_net_return": float(worst_downside),
        "stress_insolvent_paths": float(insolvent),
        "max_drawdown": float(worst_drawdown),
    }
    stress_link = EvidenceLink(
        kind="stress_study",
        identifier=f"perturbation:{study['grid']['name']}",
        content_hash=study["grid"]["identity"],
    )
    evidence: dict[str, tuple[EvidenceLink, ...]] = {
        "stress_downside_net_return": (stress_link,),
        "stress_insolvent_paths": (stress_link,),
    }
    return qualify(
        candidate_id="sf-s4-synthetic-development",
        rubric=rubric,
        expected_rubric_identity=rubric.identity,
        observations=observations,
        evidence=evidence,
        plan_hash=study["grid"]["identity"],
        decided_at="2026-08-02T00:00:00",
    )


def _figure(study: dict[str, Any], decision: QualificationDecision, destination: Path) -> None:
    """Render the four-panel Seaborn close-out figure."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import seaborn as sns

    sns.set_theme(style="whitegrid", context="talk", palette="colorblind")
    figure, axes = plt.subplots(2, 2, figsize=(19, 13))

    frame = pd.DataFrame(study["outcomes"])
    baseline = float(study["baseline"]["net_return"])
    baseline_drawdown = float(study["baseline"]["max_drawdown"])

    # Panel 1 — net-return envelope per perturbation kind, worst first.
    ordered = frame.sort_values("percentile_5")
    axis = axes[0][0]
    sns.barplot(data=ordered, y="kind", x="percentile_5", ax=axis, color="#d95f02", orient="h")
    sns.scatterplot(
        data=ordered, y="kind", x="median_net_return", ax=axis, color="#1b9e77", s=140, zorder=5
    )
    axis.axvline(baseline, color="#333333", linestyle="--", linewidth=2)
    axis.set_title(
        "Net return under frozen execution perturbation\n"
        f"bars = 5th percentile, dots = median, dashed = unperturbed ({baseline:.1%})",
        fontsize=13,
    )
    axis.set_xlabel(f"Net return over {SYNTHETIC_BARS} bars (fraction)")
    axis.set_ylabel("Perturbation kind")

    # Panel 2 — drawdown amplification, the quantity reordering actually moves.
    axis = axes[0][1]
    drawdown = frame.melt(
        id_vars="kind",
        value_vars=["median_max_drawdown", "worst_max_drawdown"],
        var_name="statistic",
        value_name="drawdown",
    )
    sns.barplot(data=drawdown, y="kind", x="drawdown", hue="statistic", ax=axis, orient="h")
    axis.axvline(baseline_drawdown, color="#333333", linestyle="--", linewidth=2)
    # Read the deepest kind off the data. A hard-coded claim here silently goes
    # stale the moment a perturbation model changes, and a caption asserting a
    # finding the figure no longer shows is worse than no caption.
    deepest = frame.loc[frame["worst_max_drawdown"].idxmin()]
    axis.set_title(
        "Maximum drawdown under perturbation\n"
        f"dashed = unperturbed ({baseline_drawdown:.1%}); deepest is "
        f"{deepest['kind']} at {deepest['worst_max_drawdown']:.1%}",
        fontsize=13,
    )
    axis.set_xlabel("Peak-to-trough drawdown (fraction, negative)")
    axis.set_ylabel("Perturbation kind")
    axis.legend(title="", loc="lower left", fontsize=10, framealpha=0.95)

    # Panel 3 — how often each perturbation was at least as bad as the baseline.
    axis = axes[1][0]
    sns.barplot(
        data=frame.sort_values("worse_than_baseline", ascending=False),
        y="kind",
        x="worse_than_baseline",
        ax=axis,
        color="#7570b3",
        orient="h",
    )
    axis.axvline(0.5, color="#333333", linestyle=":", linewidth=2)
    axis.set_xlim(0.0, 1.0)
    axis.set_title(
        "Frequency of an outcome at or below the unperturbed path\n"
        f"n = {study['grid']['replicates']} paths per kind; model frequency, not market probability",
        fontsize=13,
    )
    axis.set_xlabel("Fraction of perturbed paths")
    axis.set_ylabel("Perturbation kind")

    # Panel 4 — the qualification verdict, failures included.
    axis = axes[1][1]
    results = pd.DataFrame(
        [
            {
                "criterion": item.name,
                "status": "satisfied" if item.passed else "blocking failure",
                "value": 1.0,
            }
            for item in decision.results
        ]
    ).sort_values(["status", "criterion"])
    sns.barplot(
        data=results,
        y="criterion",
        x="value",
        hue="status",
        ax=axis,
        orient="h",
        dodge=False,
        palette={"satisfied": "#1b9e77", "blocking failure": "#d95f02"},
    )
    axis.set_xlim(0.0, 1.25)
    axis.set_xticks([])
    axis.set_xlabel("")
    axis.set_ylabel("Rubric criterion")
    blocked = len(decision.blocking_failures)
    axis.set_title(
        f"Qualification verdict: {decision.verdict}\n"
        f"rubric {decision.rubric_version} ({decision.rubric_identity[:8]}), "
        f"{blocked} blocking failure(s)",
        fontsize=13,
    )
    axis.legend(title="", loc="lower right", fontsize=10)

    figure.suptitle(
        "Signal Foundry Sprint 4 close-out — execution perturbation and strategy qualification\n"
        "Synthetic development data, simulation only. No capital at risk; no strategy qualified.",
        fontsize=16,
    )
    figure.tight_layout(rect=(0, 0, 1, 0.94))
    figure.savefig(destination, dpi=150)
    plt.close(figure)


def publish_sprint_4_evidence(output: Path | str) -> dict[str, Any]:
    """Write the sprint's evidence bundle atomically into a new directory.

    Refuses a non-empty destination so a republish cannot silently overwrite
    evidence that a report already cites.

    Raises:
        SprintEvidenceError: If the destination already holds files.
    """
    destination = Path(output)
    if destination.exists() and any(destination.iterdir()):
        raise SprintEvidenceError(
            f"{destination} is not empty; publishing into it would overwrite evidence "
            "a report may already cite"
        )
    destination.mkdir(parents=True, exist_ok=True)

    returns, costs = synthetic_candidate_path()
    grid = standard_execution_grid(replicates=STUDY_REPLICATES, root_seed=STUDY_SEED)
    study = run_perturbation_study(returns, costs, grid, expected_identity=grid.identity)
    report = failure_report(study)
    decision = sprint_4_decision(study)

    summary = {
        "sprint": "Signal Foundry Sprint 4",
        "generated_by": "alphaforge.research.sprint_4_evidence.publish_sprint_4_evidence",
        "data": "deterministic synthetic development path",
        "synthetic_seed": SYNTHETIC_SEED,
        "bars": SYNTHETIC_BARS,
        "perturbation_grid_identity": grid.identity,
        "rubric_identity": decision.rubric_identity,
        "verdict": decision.verdict,
        "blocking_failures": list(decision.blocking_failures),
        "failure_report": report,
        "limitations": [
            "Synthetic development data. Not a backtest on licensed point-in-time data.",
            "Monte Carlo frequencies come from a declared perturbation family and are "
            "not probabilities of loss in the market.",
            "The REJECTED verdict is the honest outcome for a candidate with no trial "
            "ledger, capacity measurement, or dependence-aware uncertainty evidence.",
            "No strategy is qualified, no capital is at risk, and no live or paper "
            "trading is authorized.",
        ],
        "simulation_only": True,
    }

    (destination / "perturbation_study.json").write_text(
        json.dumps(study, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (destination / "qualification_decision.json").write_text(
        json.dumps(decision.to_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (destination / "qualification_dossier.md").write_text(
        render_dossier(decision), encoding="utf-8"
    )
    (destination / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    pd.DataFrame(study["outcomes"]).to_csv(destination / "perturbation_outcomes.csv", index=False)
    _figure(study, decision, destination / "sprint_4_evidence.png")

    return summary


__all__ = [
    "STUDY_REPLICATES",
    "SYNTHETIC_BARS",
    "SYNTHETIC_SEED",
    "SprintEvidenceError",
    "publish_sprint_4_evidence",
    "sprint_4_decision",
    "synthetic_candidate_path",
]
